import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import CustomStepper from '../components/CustomStepper';
import ListOfCard from '../components/ListOfCard';
import { Grid } from '@mui/material';

export default function Home() {
  const [activeStep, setActiveStep] = React.useState(0);

  const handleNext = () => {
    setActiveStep((prevActiveStep) => prevActiveStep + 1);
  };

  const handleBack = () => {
    setActiveStep((prevActiveStep) => prevActiveStep - 1);
  };

  const handleReset = () => {
    setActiveStep(0);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Devinci Alumni
        </h1>
        <Grid container spacing={{ xs: 2, md: 3 }}>
          <Grid item xs={8}  justifyContent={'space-around'}>
          {activeStep === 2 ? <ListOfCard type={'alumni'}/> : ''}
          </Grid>
          <Grid item xs={4}>
            <CustomStepper
              activeStep={activeStep}
              handleNext={handleNext}
              handleBack={handleBack}
              handleReset={handleReset}
            />
          </Grid>
        </Grid>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
